Item rework
MignonPetitXelow/Momento pull request #5
Opened 2024-05-27 02:37 UTC by MignonPetitXelow

2024-05-28 08:10 UTC, EltyDev commented on src/main/java/org/momento/Events/PlayerShieldBlock.java
> +            if (Math.random() < (100.0 / (duraEnch + 1)) / 100.0)
Minecraft n'a pas son instance de Java.util.Random ?

2024-05-28 08:12 UTC, EltyDev commented on src/main/java/org/momento/Features/Item/ItemComponent.java
> +public interface ItemComponent extends Listener {
Intéressant pour une interface qui hériterait d'une autre interface genre "EventComponent" mais assez overkill ici

2024-05-28 08:13 UTC, EltyDev commented on src/main/java/org/momento/Momento.java
> +        new Item(Arrays.asList(new ItemStackComponent("sex", Material.COAL, 1)));
GAY SEX ? (supprime)

2024-05-28 08:15 UTC, EltyDev commented on src/main/java/org/momento/Features/Item/Item.java
> +            Bukkit.getPluginManager().registerEvents(itemComponent, Momento.plugin);
Register un event pour chaque component c'est overkill

2024-05-28 08:17 UTC, EltyDev commented on src/main/java/org/momento/Features/Item/Component/ItemStackComponent.java
> +        if(itemStack != null || name == null || material.isAir()) return itemStack;
Pourquoi si le nom est null on retourne l'itemstack ? Un item avec un nom null mais avec un modelData est théoriquement possible

2024-05-28 08:22 UTC, EltyDev commented on src/main/java/org/momento/Events/PlayerShieldBlock.java
Le principe d'un système c'est qu'il check les composants de l'entité pour pouvoir appliquer une logique selon le type et les données stocké ici on est trop bas niveau, faudrait concrétement récupérer dans nos système des entités à partir des objet bas niveau de Bukkit !

2024-05-28 08:23 UTC, EltyDev requested changes
Le concept de composant est bien compris mais pas celui de système (voir le commentaire sur PlayerShieldBlock.java)

2024-06-06 16:59 UTC, MignonPetitXelow commented on src/main/java/org/momento/Features/Item/Component/ItemStackComponent.java
> +        if(itemStack != null || name == null || material.isAir()) return itemStack;
Qui aurais l'idee d'un item sans nom? dans tout les cas name != null si name = ""

2024-06-16 16:15 UTC, EltyDev reviewed
STATIC DESTROY

2024-06-16 16:16 UTC, EltyDev requested changes
ALED

2024-07-11 07:51 UTC, EltyDev approved these changes
Ok ^^

2024-07-11 07:51 UTC, merged